#-------------------------------
# General Site Settings

title: CREA - an expert software development team
logo: nChainCREA-logo-full-hires.png
email: info@crea.si
phone: +386 1 518 66 81
address: Crea d.o.o., Brnčičeva ulica 39, 1231 Ljubljana - Črnuče, Slovenia

menu:
- {name: careers, link: '/careers/'}
- {name: Culture, link: '/Culture/'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X



#-------------------------------
# Hero Section

hero:
  hero-title: we are CREA <br>-<br> an expert software development team

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/CreaBpm/"}
- {icon: "ti-twitter", link: "https://twitter.com/crea_official"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/company/crea-d-o-o-/about/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  A company that delivers. Our biggest motivation are large scale enterprise level projects, full of technical challenges and complexity.

blurb-title: We are an expert software development team.
blurb-btn-link: '/about'
blurb-btn-name: SEARCH JOBS



#-------------------------------
# Mission (Section and Page)

# Mission Section
mission:
  Innovation, cutting edge technology and society impact of international projects we are working on are our motivation. We will continue to expand in all directions and stay a go-to expert software development company. </br></br> Time has and will continue to show the proof of our work.

mission-title: OUR MISSION


#-------------------------------
# Video Section

video:
  video-title: play video



#-------------------------------
# careers Section

careers-title: New jobs
careers:
- {
    name: Security Expert,
    icon: ti-lock,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    short-description: 'Hack much?',
    url: "#",
  }
- {
    name: Blockchain Expert,
    icon: ti-vector,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    short-description: 'If you live for C++',
    url: "#",
  }
- {
    name: BPM Expert,
    icon: ti-control-shuffle,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    short-description: 'Processes are your thing',
    url: "#",
  }


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jaka Pust"
    image: "assets/images/testimonial/employee-3.png"
    designation: "Blockchain developer"
    content: "After many years of experience in an international IT company, I decided it was time for a change in my career. I accepted a job at CREA in the field of Blockchain technologies because I think I can make a significant contribution with my years of expertise and, at the same time, learn a lot."

  - name: "Tjaša Brajlih"
    image: "assets/images/testimonial/employee-2.png"
    designation: "Software Developer"
    content: "I love it at CREA. As a new team member, I felt very welcomed by this amazing and positive team, which is always available to help me with any questions I have. I enjoy our morning coffee, as well. It's an excellent opportunity to find solutions to any work obstacles. We have several team building events every year, where you can relax and get to know colleagues better. Even though I have a long commute, I cannot wait to get to work every day."
  
  - name: "Andrej Vilhar"
    image: "assets/images/testimonial/employee-1.png"
    designation : "Project Manager"
    content : "CREA provides me with exciting professional challenges and, more importantly, the opportunity for personal growth. We have a fantastic working environment and a great team that makes you feel good day in day out. It's not every day that you can say that about your job, but at CREA, I found the perfect balance.
"
    
  - name: "Adriana Jereb"
    image: "assets/images/testimonial/employee-4.png"
    designation : "Software developer"
    content : "Great and positive relationships with my co-workers are most important to me."
    
  - name: "Matjaž Kobal"
    image: "assets/images/testimonial/employee-5.png"
    designation : "Business Analysist"
    content : "I've been at CREA for the eleventh year, having previously 'held' for a maximum of 4 years with the same employer. I think that speaks for itself."
    
#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: ""
    url: "#"



#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: info@crea.si